name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^2.0.2
  open_file: ^3.2.1
  geolocator: ^7.0.3
  http: ^0.13.3
  flutter_spinkit: ^4.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  modal_progress_hud: ^0.1.3
  draw_graph: ^0.0.2
  pdf: ^3.4.2
  google_maps_flutter: ^2.0.6
  syncfusion_flutter_pdf: ^19.2.44-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900